### ISSUE TITLE
SyntaxError after install

### ISSUE THREAD

**Issue by Aareon** [wasi0013/PyTM#254]
```
File "...\PyTM-f4mTLz1x\Lib\site-packages\python_pytm-0.0.12-py3.11.egg\PyTM\cli.py", line 98
    table.add_row(key, f'{datetime.datetime.fromisoformat(value['created_at']).strftime("%Y, %B, %d, %H:%M:%S %p")}', value['status'])
                                                                 ^^^^^^^^^^
SyntaxError: f-string: unmatched '['
```

**Comment by Aareon** [comment]
Due to usage of single quotes within a single-quoted f-string.

**Comment by wasi0013** [comment]
Which python version are you running? Python 3.11?

Only Python 3.12 is supported for now.

**Comment by wasi0013** [comment]
I just noticed you've forked the repo, if you are working on a fix, feel free to create a pull request when you are done.

**Comment by Aareon** [comment]
Are there any dependencies that require 3.12+? Would it be acceptable to bring compatibility with 3.11? I noticed that there are stub functions that are shadowing other functions in `cli.py`, is that intended behavior?

**Comment by wasi0013** [comment]
> Are there any dependencies that require 3.12+?

No. Currently, there are two dependencies: `click` & `rich`. There is a possibility of exploring `textual` in the future. But, it should also be compatible with lower Python versions.
 
> Would it be acceptable to bring compatibility with 3.11?

Absolutely. I wanted to develop the core features first, and then improve the test coverage before diving into compatibility.

> I noticed that there are stub functions that are shadowing other functions in cli.py, is that intended behavior?

Nope! This is not intended. Thanks, for the catch, will fix it.

**Comment by wasi0013** [comment]
I've fixed the f-string issues, and renamed stub functions so that they don't shadow other functions. Thanks, @Aareon for pointing it out!
