### ISSUE TITLE
SyntaxError: f-string expression part cannot include a backslash

### ISSUE THREAD

**Issue by Kaschmiri** [wasi0013/PyTM#257]
**Describe the bug**
SyntaxError: f-string expression part cannot include a backslash
> pytm --version
Traceback (most recent call last):
  File "../bin/pytm", line 5, in <module>
    from PyTM.cli import cli
  File "../lib/python3.10/site-packages/PyTM/cli.py", line 16, in <module>
    from PyTM.core import data_handler, invoice_handler
  File "../lib/python3.10/site-packages/PyTM/core/invoice_handler.py", line 116
    """

Python version: 3.10.11

**Comment by wasi0013** [comment]
Thanks for checking it out. Try using the latest version of Python: [Python 3.12](https://www.python.org/downloads/release/python-3120/) and let me know if you still face any issues.

**Comment by Kaschmiri** [comment]
Since python 3.12 is new- too new for me to update most of my environments, yet- I strongly recommend mentioning that only 3.12 is supported on [your readthedocs.io page](https://pytm.readthedocs.io/).

**Comment by wasi0013** [comment]
Thanks, I've updated the README.md. You can install Python 3.12 using [pyenv](https://realpython.com/intro-to-pyenv/) without messing up your environment. Or, try using [virtualenv](https://virtualenv.pypa.io/en/latest/)
